version: "3"

services:
  valheim:
    image: mbround18/valheim:latest
    container_name: valheim_server
    restart: always
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
      - 8074:8074
    environment:
      - PORT=2456
      - NAME="Valheim - Krasosu"
      - WORLD="Alderaan"
      - PASSWORD=${SERVER_PASSWORD}
      - TZ=America/Chicago
      - PUBLIC=1
      - AUTO_UPDATE=0
      - AUTO_UPDATE_SCHEDULE="0 */1 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="*/15 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=7
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - WEBHOOK_URL=${WEBHOOK_URL}
      - UPDATE_ON_STARTUP=1
      - ADDRESS=94.16.109.118
      - HTTP_PORT=8074
    volumes:
      - ./saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./server:/home/steam/valheim
      - ./backups:/home/steam/backups
    networks:
      - web

networks:
  web:
    external: true
